# Generated by Django 4.1.3 on 2022-11-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SurfSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=64)),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], default='EU', max_length=2)),
                ('best_wind', models.CharField(choices=[('N', 'North'), ('NE', 'North East'), ('E', 'East'), ('SE', 'South East'), ('S', 'South'), ('SW', 'South West'), ('W', 'West'), ('NW', 'North West')], default=None, max_length=2)),
                ('wave_direction', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], default='B', max_length=1)),
                ('spot_type', models.CharField(choices=[('B', 'Beach'), ('R', 'Reef'), ('P', 'Point'), ('H', 'Headland'), ('C', 'Cove'), ('L', 'Lagoon'), ('O', 'Other')], default='B', max_length=1)),
                ('wave_type', models.CharField(choices=[('G', 'Gentle'), ('M', 'Moderate'), ('H', 'Heavy'), ('E', 'Extreme')], default='G', max_length=1)),
                ('swell_size', models.IntegerField(choices=[(1, '1-3 ft.'), (2, '3-6 ft.'), (3, '6-9 ft.'), (4, '9-12 ft.'), (5, '12+ ft.')], default=1)),
                ('crowd', models.IntegerField(choices=[(1, 'Empty'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Full')])),
                ('best_season', models.IntegerField(choices=[(1, 'Winter'), (2, 'Spring'), (3, 'Summer'), (4, 'Autumn')])),
                ('difficulty', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Pro')])),
                ('danger', models.ManyToManyField(blank=True, null=True, to='guide.danger')),
            ],
        ),
    ]
