# Generated by Django 4.1.3 on 2022-11-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seasons',
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='best_wind',
            field=models.CharField(choices=[('N', 'North'), ('NE', 'North East'), ('E', 'East'), ('SE', 'South East'), ('S', 'South'), ('SW', 'South West'), ('W', 'West'), ('NW', 'North West')], max_length=2),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='continent',
            field=models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=2),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='spot_type',
            field=models.CharField(choices=[('B', 'Beach'), ('R', 'Reef'), ('P', 'Point'), ('H', 'Headland'), ('C', 'Cove'), ('L', 'Lagoon'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='swell_size',
            field=models.IntegerField(choices=[(1, '1-3 ft.'), (2, '3-6 ft.'), (3, '6-9 ft.'), (4, '9-12 ft.'), (5, '12+ ft.'), (6, '20+ ft.')]),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='wave_type',
            field=models.CharField(choices=[('G', 'Gentle'), ('M', 'Moderate'), ('H', 'Heavy'), ('E', 'Extreme')], max_length=1),
        ),
    ]
