# Generated by Django 4.1.3 on 2022-11-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_delete_seasons_alter_surfspot_best_wind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='best_wind',
            field=models.CharField(choices=[('N', 'North'), ('NE', 'North-East'), ('E', 'East'), ('SE', 'South-East'), ('S', 'South'), ('SW', 'South-West'), ('W', 'West'), ('NW', 'North-West')], max_length=13),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='swell_size',
            field=models.IntegerField(blank=True, choices=[(1, '1-3 ft.'), (2, '3-6 ft.'), (3, '6-9 ft.'), (4, '9-12 ft.'), (5, '12+ ft.'), (6, '20+ ft.')], default=1, help_text='Swell size in feet', null=True, verbose_name='Swell size'),
        ),
    ]
