# Generated by Django 4.1.3 on 2022-11-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_surfspot_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='continent',
            field=models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=2),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='spot_type',
            field=models.CharField(choices=[('B', 'Beach break'), ('R', 'Reef break'), ('P', 'Point break'), ('O', 'Other break')], max_length=1),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='swell_size',
            field=models.IntegerField(choices=[(1, '1-3 ft.'), (2, '3-6 ft.'), (3, '6-9 ft.'), (4, '9-12 ft.'), (5, '12+ ft.'), (6, '20+ ft.')]),
        ),
    ]
