# Generated by Django 4.1.3 on 2022-11-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_alter_surfspot_continent_alter_surfspot_spot_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspot',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
