# Generated by Django 4.1.3 on 2022-11-29 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0008_photogallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoGallery',
            new_name='Photo',
        ),
    ]
