# Generated by Django 4.1.3 on 2022-11-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_remove_userinformation_avatar_surfspot_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=128),
        ),
    ]
