# Generated by Django 4.1.3 on 2022-11-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspot',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
