# Generated by Django 4.1.3 on 2022-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_surfspot_map_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surfspot',
            name='map_url',
        ),
        migrations.AddField(
            model_name='surfspot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='surfspot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
