# Generated by Django 4.1.3 on 2022-12-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0015_remove_surfspot_latitude_remove_surfspot_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='surfspot',
            name='best_season',
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.season')),
            ],
        ),
        migrations.AddField(
            model_name='surfspot',
            name='season',
            field=models.ManyToManyField(blank=True, to='guide.season'),
        ),
    ]
