# Generated by Django 4.1.3 on 2022-12-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0016_season_remove_surfspot_best_season_temperature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surfspot',
            old_name='season',
            new_name='best_season',
        ),
        migrations.AddField(
            model_name='surfspot',
            name='temperature_in_fall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surfspot',
            name='temperature_in_spring',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surfspot',
            name='temperature_in_summer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surfspot',
            name='temperature_in_winter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='wave_direction',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
