# Generated by Django 4.1.3 on 2022-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0017_rename_season_surfspot_best_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='best_season',
            field=models.ManyToManyField(related_name='best_season', to='guide.season'),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='continent',
            field=models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=2),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Pro')], null=True),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='continent',
            field=models.CharField(blank=True, choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=2, null=True),
        ),
    ]
