# Generated by Django 4.1.4 on 2022-12-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0018_alter_surfspot_best_season_alter_surfspot_continent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.season')),
                ('surf_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.surfspot')),
            ],
        ),
    ]
